### ISSUE TITLE
XML Parsing Broken on ToO Branch

### ISSUE THREAD

**Issue by tventers** [NuSpaceSim/nuSpaceSim#36]
Two issues:
1. It's not obvious how to create an XML file for ToO calculations (does the create-config command do this? if so, how?).
2. The XML file generated by the create-config command in the example cannot be parsed -- I get a run-time error stating that the XML file is invalid.

**Comment by tventers** [comment]
Update --

I get the following error when running the create-config command:
Traceback (most recent call last):
  File "/Users/tventers/anaconda3/envs/nss_too_dev/bin/nuspacesim", line 8, in <module>
    sys.exit(cli())
  File "/Users/tventers/anaconda3/envs/nss_too_dev/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tventers/anaconda3/envs/nss_too_dev/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/tventers/anaconda3/envs/nss_too_dev/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tventers/anaconda3/envs/nss_too_dev/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tventers/anaconda3/envs/nss_too_dev/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tventers/Work/nuSpaceSim/Testing/nuSpaceSim-ToO/nuSpaceSim/src/nuspacesim/apps/cli.py", line 255, in create_config
    create_xml(filename, NssConfig(simulation=simulation))
  File "/Users/tventers/Work/nuSpaceSim/Testing/nuSpaceSim-ToO/nuSpaceSim/src/nuspacesim/xml_config/parse_config.py", line 442, in create_xml
    detra.text = str(config.detector.ra_start)
AttributeError: 'DetectorCharacteristics' object has no attribute 'ra_start'

**Comment by Areustle** [comment]
Related to #32

**Comment by Areustle** [comment]
Mostly Resolved needs testing.

**Comment by Areustle** [comment]
Fixed and obviated with toml configuration file.
