### ISSUE TITLE
Version 1.2.7 does not work with Version 2 of the nuPyProp Tables

### ISSUE THREAD

**Issue by jfkrizmanic** [NuSpaceSim/nuSpaceSim#65]
Here is what the program reports, note Ver 3 of the tables do work:

```
Traceback (most recent call last):
  File "/Users/jkrizman/anaconda3/bin/nuspacesim", line 8, in <module>
    sys.exit(cli())
  File "/Users/jkrizman/anaconda3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jkrizman/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/jkrizman/anaconda3/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jkrizman/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jkrizman/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jkrizman/anaconda3/lib/python3.7/site-packages/nuspacesim/apps/cli.py", line 199, in run
    write_stages=write_stages,
  File "/Users/jkrizman/anaconda3/lib/python3.7/site-packages/nuspacesim/compute.py", line 143, in compute
    tau = Taus(config)
  File "/Users/jkrizman/anaconda3/lib/python3.7/site-packages/nuspacesim/simulation/taus/taus.py", line 87, in __init__
    self.pexit_grid = NssGrid.read(file, path="/", format="hdf5")
  File "/Users/jkrizman/anaconda3/lib/python3.7/site-packages/nuspacesim/utils/grid.py", line 76, in __call__
    return registry.read(self._cls, *args, **kwargs)
  File "/Users/jkrizman/anaconda3/lib/python3.7/site-packages/astropy/io/registry.py", line 527, in read
    data = reader(*args, **kwargs)
  File "/Users/jkrizman/anaconda3/lib/python3.7/site-packages/nuspacesim/utils/grid.py", line 327, in hdf5_nssgrid_reader
    griddata = f[path]["__nss_grid_data__"][()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/jkrizman/anaconda3/lib/python3.7/site-packages/h5py/_hl/group.py", line 305, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object '__nss_grid_data__' doesn't exist)"
```

**Comment by Areustle** [comment]
We have elected to reformat the v2 (and v1) tables and drop the `no regen` data.
